[theme]
base="dark"
primaryColor="#3B82F6"
backgroundColor="#0B0E14"
secondaryBackgroundColor="#111827"
textColor="#E3E5E8"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"
